CREATE DATABASE prj1;
use prj1;

CREATE TABLE Board (
	id INT PRIMARY KEY AUTO_INCREMENT,
	title VARCHAR(255) NOT NULL,
    content VARCHAR(1000) NOT NULL
);

SELECT *
FROM Board;

ALTER TABLE Board
ADD COLUMN writer VARCHAR(255) NOT NULL;

ALTER TABLE Board
ADD COLUMN inserted DATETIME NOT NULL DEFAULT NOW();